## numpy
- numerical python 
- its works as creating arrays and mathematical operations andstastical operatiions



In [2]:
# importing numpy
import numpy as np

In [5]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [7]:
len(dir(np))

620

In [8]:
# creating an array 
a1=np.array([1,2,3,4,5])

In [9]:
a1

array([1, 2, 3, 4, 5])

In [11]:
a1.ndim

1

In [12]:
a1.size

5

In [13]:
a1.shape

(5,)

In [32]:
a2=[np.array([[1,2,3,4,5]])]

In [19]:
a3=np.arange(1,31)

In [20]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [21]:
a3.ndim



1

In [23]:
a3.reshape(2,15)



array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [24]:
a3.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [35]:
a4=a3.reshape(2,15)


In [36]:
a4.shape

(2, 15)

In [37]:
a5=a3.reshape(3,10)

In [38]:
a5[1:2,5:6]

array([[16]])

In [44]:
a4[1:2,1:10:2]





array([[17, 19, 21, 23, 25]])

In [47]:
a5=a3.reshape(6,5)


In [48]:
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
a5[4:6,1:5]


array([[23, 24, 25],
       [28, 29, 30]])

In [65]:
a5[0:6:5,1:5:3]


array([[ 2,  5],
       [27, 30]])

In [68]:
np.random.rand(1,10)


array([[0.43130339, 0.05500158, 0.2237458 , 0.69294584, 0.42276903,
        0.99221016, 0.69799145, 0.87366082, 0.48193377, 0.11483111]])

In [71]:
np.random.randn(1,10)



array([[ 0.60244874,  0.12640467,  0.81499225,  0.10524504, -1.5634625 ,
        -0.39091482, -0.15526296,  0.13180086, -0.22652185,  1.97428343]])

In [75]:
np.random.randint(1,100,10)





array([ 4, 84, 58, 12, 26, 45, 91, 44, 94, 76])

In [2]:
a3=np.random.randint(1,1000,100)
a3[a3%2==0]


NameError: name 'np' is not defined

In [10]:
a3

NameError: name 'a3' is not defined

In [2]:
import numpy as np 
a4=np.ones((5,5),int)
a4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
a5=np.zeros((5,5),int)
a5

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
np.vstack((a4,a5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.hstack((a4,a5))

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [22]:
np.hsplit(a4,5)

[array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]])]

In [26]:
np.linspace(1,10,100)


array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [3]:
np.linspace(1,1000,100)

array([   1.        ,   11.09090909,   21.18181818,   31.27272727,
         41.36363636,   51.45454545,   61.54545455,   71.63636364,
         81.72727273,   91.81818182,  101.90909091,  112.        ,
        122.09090909,  132.18181818,  142.27272727,  152.36363636,
        162.45454545,  172.54545455,  182.63636364,  192.72727273,
        202.81818182,  212.90909091,  223.        ,  233.09090909,
        243.18181818,  253.27272727,  263.36363636,  273.45454545,
        283.54545455,  293.63636364,  303.72727273,  313.81818182,
        323.90909091,  334.        ,  344.09090909,  354.18181818,
        364.27272727,  374.36363636,  384.45454545,  394.54545455,
        404.63636364,  414.72727273,  424.81818182,  434.90909091,
        445.        ,  455.09090909,  465.18181818,  475.27272727,
        485.36363636,  495.45454545,  505.54545455,  515.63636364,
        525.72727273,  535.81818182,  545.90909091,  556.        ,
        566.09090909,  576.18181818,  586.27272727,  596.36363

In [6]:
a6=np.eye(4,5)
np.diagonal(a6)

array([1., 1., 1., 1.])

In [7]:
a7=np.arange(1,31)

In [8]:
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [10]:
a8=a7.reshape(6,5)

In [11]:
a8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
a8.diagonal()

array([ 1,  7, 13, 19, 25])

In [14]:
a8.min()


1

In [15]:
a8.max()

30

In [17]:
a8.mean()


15.5

In [18]:
a8.std()

8.65544144839919

In [23]:
a8.sum()

465

In [25]:
a8.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351,
       378, 406, 435, 465], dtype=int32)

In [27]:
a8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [29]:
a8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
a8.transpose()

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [35]:
a8.dot(88)


array([[  88,  176,  264,  352,  440],
       [ 528,  616,  704,  792,  880],
       [ 968, 1056, 1144, 1232, 1320],
       [1408, 1496, 1584, 1672, 1760],
       [1848, 1936, 2024, 2112, 2200],
       [2288, 2376, 2464, 2552, 2640]])

In [37]:
a8.argmax()

29

In [40]:
a8.argmin()

0

In [42]:
a8.prod()

1409286144

In [43]:
## saving the array loading the arrray
 
    

In [44]:
n=np.array([[[1,2],[6,7]]])

In [45]:
n

array([[[1, 2],
        [6, 7]]])

In [47]:
n.shape


(1, 2, 2)

In [50]:
np.save("hello world",n)

In [54]:
x=np.load("hello world.npy")
x

array([[[1, 2],
        [6, 7]]])

In [55]:
np.exp(np.arange(1,11))

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [60]:
np.percentile(a8,5)

2.45

In [63]:
np.sin(a8)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175],
       [ 0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162]])

In [65]:
np.tan(a8)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01],
       [ 3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01,  2.23716094e+00],
       [-1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
        -2.13489670e+00, -1.33526407e-01],
       [ 1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
         8.87142844e-01, -6.40533120e+00]])

In [68]:
np.cos(a8) 

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206],
       [-0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281],
       [ 0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145]])

In [70]:
np.cosh(a8)

array([[1.54308063e+00, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
        7.42099485e+01],
       [2.01715636e+02, 5.48317035e+02, 1.49047916e+03, 4.05154203e+03,
        1.10132329e+04],
       [2.99370709e+04, 8.13773957e+04, 2.21206696e+05, 6.01302142e+05,
        1.63450869e+06],
       [4.44305526e+06, 1.20774764e+07, 3.28299846e+07, 8.92411505e+07,
        2.42582598e+08],
       [6.59407867e+08, 1.79245642e+09, 4.87240172e+09, 1.32445611e+10,
        3.60024497e+10],
       [9.78648047e+10, 2.66024120e+11, 7.23128532e+11, 1.96566715e+12,
        5.34323729e+12]])

In [72]:
np.tanh(a8)

array([[0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ],
       [0.99998771, 0.99999834, 0.99999977, 0.99999997, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [74]:
a9=np.arrange(1,101)
max(60<=101)

AttributeError: module 'numpy' has no attribute 'arrange'

In [82]:
 for i in range(65,91):
    print(chr(i),'->',i%2==0)

A -> False
B -> True
C -> False
D -> True
E -> False
F -> True
G -> False
H -> True
I -> False
J -> True
K -> False
L -> True
M -> False
N -> True
O -> False
P -> True
Q -> False
R -> True
S -> False
T -> True
U -> False
V -> True
W -> False
X -> True
Y -> False
Z -> True


In [ ]:
import time,webbrowser
browsers=3
count=0
while count<=browsers:
    time.sleep(10)
    if count==1:
        webbrowser.open("http://apssdc.in")
    elif count==2:
        webbrowser.open("http://gmail.com")
    elif count==3:
        webbrowser.open("http://yahoo.com")
    count+=1
        
        